const SECTIONS = [
  { r: "Super Sugo", label: "Super Sugo Legends" },
  { r: "Anniversary Sugo", label: "Anniversary Legends" },
  { r: "Rumble Sugo", label: "Pirate Rumble Legends" },
  { r: "Treasure Map", label: "Treasure Map Legends" },
  { r: "Kizuna Sugo", label: "Kizuna Clash Legends" },
  { r: "Standard", label: "Regular Legends" }
];

const UNITS = [
  { id: "ss4571", name: "Imu", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4564", name: "Buggy the Genius Jester", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4562", name: "Blackbeard", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss4560", name: "Red-Haired Shanks", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4558", name: "Monkey D. Luffy", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss4549", name: "Eustass Kid", r: "Super Sugo", t: "STR", is_plus: true, base_id: "ss3338" },
  { id: "ss4492", name: "Bartholomew Kuma", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4491", name: "St. Jaygarcia Saturn", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4490", name: "Luffy & Bonney", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4453", name: "St. Marcus Mars", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4451", name: "St. Topman Warcury", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss4443", name: "St. Ethanbaron V. Nusjuro", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss4441", name: "St. Shepherd Ju Peter", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss4432", name: "Monkey D. Luffy", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss4388", name: "Newgate & Shiki & Linlin", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4387", name: "Roger & Rayleigh & Gaban", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4380", name: "St. Jaygarcia Saturn", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4366", name: "Kizaru", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss4365", name: "Luffy & Zoro & Sanji", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss4293", name: "Whitebeard & Ace", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4292", name: "Sabo", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4290", name: "Monkey D. Luffy", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4231", name: "Shanks VS Kid", r: "Super Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "ss4219", name: "Blackbeard VS Law", r: "Super Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "ss4212", name: "Yamato from ONE PIECE magazine", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4211", name: "Luffy VS Kaido", r: "Super Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "ss4162", name: "Monkey D. Luffy", r: "Super Sugo", t: "DEX", is_plus: true, base_id: "ss3607" },
  { id: "ss4154", name: "Portgas D. Ace from ONE PIECE magazine", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss4153", name: "Shanks", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss4150", name: "Monkey D. Luffy", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss4063", name: "Trafalgar Law", r: "Super Sugo", t: "DEX", is_plus: true, base_id: "ss3336" },
  { id: "ss4062", name: "Zoro & Sanji", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4060", name: "Yamato", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss4058", name: "Roger & Oden", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss3984", name: "Kaido", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3973", name: "Olin the Oiran", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss3971", name: "Law & Kid", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3957", name: "Monkey D. Luffy", r: "Super Sugo", t: "PSY", is_plus: true, base_id: "ss3956" },
  { id: "ss3956", name: "Monkey D. Luffy", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss3896", name: "Roronoa Zoro", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss3889", name: "Sanji", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss3878", name: "Luffy & Yamato", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3816", name: "Uta", r: "Super Sugo", t: "QCK", is_plus: true, base_id: "ss3721" },
  { id: "ss3814", name: "Monkey D. Luffy", r: "Super Sugo", t: "QCK", is_plus: true, base_id: "ss3334" },
  { id: "ss3792", name: "Nico Robin", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss3790", name: "Nami", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss3788", name: "Kaido VS Yamato", r: "Super Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "ss3786", name: "Gol D. Roger", r: "Super Sugo", t: "PSY", is_plus: true, base_id: "ss3177" },
  { id: "ss3721", name: "Uta", r: "Super Sugo", t: "INT", is_plus: true, base_id: "ss3680" },
  { id: "ss3706", name: "Monkey D. Luffy", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss3695", name: "Red-Haired Shanks", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss3680", name: "Uta", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss3611", name: "Yamato & Ace", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3609", name: "Kaido", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3607", name: "Monkey D. Luffy", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss3519", name: "Kozuki Oden", r: "Super Sugo", t: "STR", is_plus: true, base_id: "ss3175" },
  { id: "ss3515", name: "Luffy & Straw Hat Pirates", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3513", name: "Roger & Newgate", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3430", name: "Yamato", r: "Super Sugo", t: "PSY", is_plus: true, base_id: "ss3429" },
  { id: "ss3429", name: "Yamato", r: "Super Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ss3338", name: "Eustass Kid", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ss3336", name: "Trafalgar Law", r: "Super Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ss3334", name: "Monkey D. Luffy", r: "Super Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ss3177", name: "Gol D. Roger", r: "Super Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "ss3175", name: "Kozuki Oden", r: "Super Sugo", t: "STR", is_plus: false, base_id: null },

  { id: "an4529", name: "St. Peter & St. Warcury", r: "Anniversary Sugo", t: "TAG", is_plus: false, base_id: null },
  { id: "an4529", name: "St. Mars & St. Saturn", r: "Anniversary Sugo", t: "TAG", is_plus: false, base_id: null },
  { id: "an4529", name: "Zoro VS St. Nusjuro", r: "Anniversary Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "an4522", name: "Blackbeard & Kuzan", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4521", name: "Garp & Coby", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4477", name: "Kaido & Big Mom", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4476", name: "Yamato & Momonosuke", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4469", name: "Zoro VS Lucci", r: "Anniversary Sugo", t: "VS", is_plus: false, base_id: null },
  { id: "an4418", name: "Boa Hancock from ONE PIECE magazine", r: "Anniversary Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "an4391", name: "Dragon & Ivankov & Kuma", r: "Anniversary Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "an4371", name: "Roronoa Zoro", r: "Anniversary Sugo", t: "QCK", is_plus: true, base_id: "an3755" },
  { id: "an4367", name: "Nami from ONE PIECE magazine", r: "Anniversary Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "an4329", name: "S", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4323", name: "Zoro & Kaku", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4322", name: "Luffy & Lucci", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4294", name: "Hancock & Nami & Robin", r: "Anniversary Sugo", t: "INT", is_plus: true, base_id: "an3613" },
  { id: "an4275", name: "Oden & Kin'emon & Denjiro", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4268", name: "Big Mom & Katakuri", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4267", name: "Kaido & King", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4257", name: "Roger & Rayleigh & Gaban", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4151", name: "King of Pirates - Gol D. Roger", r: "Anniversary Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "an4111", name: "Buggy & Crocodile & Mihawk", r: "Anniversary Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "an4100", name: "Blackbeard", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4029", name: "Coby", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4012", name: "Monkey D. Luffy", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an4011", name: "Shanks", r: "Anniversary Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "an3880", name: "Oden & Toki", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an3839", name: "Sabo", r: "Anniversary Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "an3832", name: "Monkey D. Luffy", r: "Anniversary Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "an3830", name: "Portgas D. Ace", r: "Anniversary Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "an3755", name: "Roronoa Zoro", r: "Anniversary Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "an3745", name: "Kin'emon & Denjiro & Ashura Doji & Dogstorm", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "an3613", name: "Hancock & Nami & Robin", r: "Anniversary Sugo", t: "STR", is_plus: false, base_id: null },

  { id: "pr4579", name: "Kami Eneru", r: "Rumble Sugo", t: "PSY", is_plus: true, base_id: "pr3245" },
  { id: "pr4556", name: "Portgas D. Ace", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr4543", name: "Kaku", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr4528", name: "Prince Grus", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr4512", name: "Kujaku", r: "Rumble Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "pr4498", name: "Stussy", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr4482", name: "Master Caesar Clown", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr4466", name: "San Juan Wolf", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr4449", name: "S-Snake", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr4431", name: "Jinbe", r: "Rumble Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "pr4424", name: "Borsalino", r: "Rumble Sugo", t: "DEX", is_plus: true, base_id: "pr3411" },
  { id: "pr4343", name: "Pica", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr4328", name: "Edward Weevil", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr4321", name: "Kuzan", r: "Rumble Sugo", t: "QCK", is_plus: true, base_id: "pr2930" },
  { id: "pr4313", name: "Sentomaru", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr4306", name: "Bartholomew Kuma", r: "Rumble Sugo", t: "STR", is_plus: true, base_id: "pr3427" },
  { id: "pr4299", name: "Fujitora & Ryokugyu", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr4281", name: "Dr. Vegapunk - York", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr4247", name: "Avalo Pizarro", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr4226", name: "S-Bear", r: "Rumble Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "pr4217", name: "Fleet Admiral Sakazuki", r: "Rumble Sugo", t: "STR", is_plus: true, base_id: "pr3157" },
  { id: "pr4132", name: "S-Shark", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr4109", name: "S-Hawk", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr4048", name: "Shinobu & Raizo", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr3954", name: "Kawamatsu the Kappa", r: "Rumble Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "pr3905", name: "Emporio Ivankov", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr3859", name: "Scratchmen Apoo", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr3772", name: "Page One", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr3752", name: "Orochi", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr3730", name: "Garp the Fist", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr3637", name: "Charlotte Smoothie", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "pr3582", name: "Urouge", r: "Rumble Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "pr3427", name: "Bartholomew Kuma", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr3411", name: "Borsalino", r: "Rumble Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "pr3245", name: "Kami Eneru", r: "Rumble Sugo", t: "PSY", is_plus: false, base_id: null },
  { id: "pr3157", name: "Sakazuki", r: "Rumble Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "pr2930", name: "Kuzan", r: "Rumble Sugo", t: "QCK", is_plus: false, base_id: null },

  { id: "tm4544", name: "Kizaru", r: "Treasure Map", t: "INT", is_plus: false, base_id: null },
  { id: "tm4515", name: "Rebecca", r: "Treasure Map", t: "QCK", is_plus: false, base_id: null },
  { id: "tm4499", name: "Dr. Vegapunk", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm4483", name: "Sanji & Reiju", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm4419", name: "Sabo", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm4401", name: "Portgas D. Ace", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm4345", name: "Tashigi", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },
  { id: "tm4314", name: "Buggy", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm4300", name: "Morley & Karasu", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm4282", name: "Stussy", r: "Treasure Map", t: "INT", is_plus: false, base_id: null },
  { id: "tm4274", name: "Sir Crocodile", r: "Treasure Map", t: "DEX", is_plus: true, base_id: "tm3483" },
  { id: "tm4250", name: "Coby", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },
  { id: "tm4227", name: "Lucci & Kaku", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm4193", name: "Franky", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm4179", name: "Usopp", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm4133", name: "Dr. Vegapunk - Atlas", r: "Treasure Map", t: "INT", is_plus: false, base_id: null },
  { id: "tm4071", name: "Monkey D. Luffy", r: "Treasure Map", t: "QCK", is_plus: false, base_id: null },
  { id: "tm4050", name: "Ryokugyu", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm4003", name: "Nami & Carina", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm3933", name: "Nami & Carrot", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm3861", name: "Jewelry Bonney", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },
  { id: "tm3775", name: "Jinbe", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },
  { id: "tm3735", name: "Hina", r: "Treasure Map", t: "QCK", is_plus: false, base_id: null },
  { id: "tm3641", name: "Blackbeard", r: "Treasure Map", t: "INT", is_plus: false, base_id: null },
  { id: "tm3563", name: "Izo & Kikunojo", r: "Treasure Map", t: "QCK", is_plus: false, base_id: null },
  { id: "tm3543", name: "Carrot & Wanda", r: "Treasure Map", t: "STR", is_plus: false, base_id: null },
  { id: "tm3523", name: "Mr. 2 Bon Clay", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },
  { id: "tm3483", name: "Sir Crocodile", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm3462", name: "Koala: Rowdy Halloween Party", r: "Treasure Map", t: "DEX", is_plus: false, base_id: null },
  { id: "tm3364", name: "Sanji", r: "Treasure Map", t: "PSY", is_plus: false, base_id: null },

  { id: "ki4547", name: "Beckman & Yasopp", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4532", name: "Doc Q & Strongheart", r: "Kizuna Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ki4518", name: "Shinobu & Otama", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4502", name: "Drake & Apoo", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4487", name: "Dr. Vegapunk - Atlas", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4472", name: "Donquixote Pirates", r: "Kizuna Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ki4456", name: "Vasco Shot", r: "Kizuna Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ki4436", name: "Dorry & Broggy", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4422", name: "Bonney Pirates", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4405", name: "Mr. 0 & Miss All Sunday", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4392", name: "Ginny", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki4348", name: "Sabo & Bonney", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4333", name: "Kalifa", r: "Kizuna Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ki4319", name: "Chopper & Robin", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4303", name: "Sai & Leo", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4287", name: "Sanji & Pudding", r: "Kizuna Sugo", t: "STR", is_plus: true, base_id: "ki3204" },
  { id: "ki4285", name: "Shaka the Good & Edison the Thinker & Pythagoras the Wise", r: "Kizuna Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ki4253", name: "Shiryu", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4216", name: "Edward Newgate", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki4197", name: "Brook", r: "Kizuna Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ki4182", name: "Tony Tony Chopper", r: "Kizuna Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ki4167", name: "S", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki4137", name: "Dr. Vegapunk", r: "Kizuna Sugo", t: "INT", is_plus: false, base_id: null },
  { id: "ki4115", name: "Tobi Roppo", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki4054", name: "Otama", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki4008", name: "Ain", r: "Kizuna Sugo", t: "QCK", is_plus: false, base_id: null },
  { id: "ki3967", name: "Vinsmoke Reiju", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki3917", name: "Doflamingo & Crocodile", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3824", name: "Charlotte Perospero", r: "Kizuna Sugo", t: "DEX", is_plus: false, base_id: null },
  { id: "ki3780", name: "Boa Hancock", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3590", name: "X Drake", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3508", name: "Kaido & Lead Performers", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3391", name: "Toki & Momonosuke & Hiyori", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3349", name: "Ace & Sabo", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3300", name: "Firetank Pirates", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },
  { id: "ki3204", name: "Sanji & Pudding", r: "Kizuna Sugo", t: "STR", is_plus: false, base_id: null },

  { id: "st5014", name: "Monkey D. Luffy", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4551", name: "Burgess & Shiryu", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4550", name: "Crocodile & Mihawk", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4537", name: "Luffy & Broggy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4536", name: "Usopp & Dorry", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4535", name: "Smoker", r: "Standard", t: "QCK", is_plus: true, base_id: "st3007" },
  { id: "st4523", name: "Hibari", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4520", name: "Ulti & Page One", r: "Standard", t: "STR", is_plus: true, base_id: "st3433" },
  { id: "st4507", name: "Nami & Vivi", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4506", name: "Hancock & Sandersonia & Marigold", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4505", name: "Kaido", r: "Standard", t: "DEX", is_plus: true, base_id: "st2700" },
  { id: "st4493", name: "Emet", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4489", name: "Shirahoshi & Mansherry", r: "Standard", t: "STR", is_plus: true, base_id: "st3166" },
  { id: "st4475", name: "Luffy & Law", r: "Standard", t: "STR", is_plus: true, base_id: "st2534" },
  { id: "st4465", name: "Shanks: Moon Knight Emperor", r: "Standard", t: "INT", is_plus: true, base_id: "st3118" },
  { id: "st4460", name: "Van Ogre", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4459", name: "Catarina Devon", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4458", name: "Blackbeard", r: "Standard", t: "STR", is_plus: true, base_id: "st3280" },
  { id: "st4439", name: "Nami & Usopp", r: "Standard", t: "STR", is_plus: true, base_id: "st3493" },
  { id: "st4433", name: "Bartholomew Kuma", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4426", name: "Brook", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4425", name: "Franky", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4410", name: "St. Figarland Garling", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4409", name: "Monkey D. Garp", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4408", name: "Mihawk & Perona", r: "Standard", t: "STR", is_plus: true, base_id: "st2895" },
  { id: "st4395", name: "Yamato & Otama", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4394", name: "Nami", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4393", name: "Sabo & Koala", r: "Standard", t: "STR", is_plus: true, base_id: "st2561" },
  { id: "st4381", name: "Jewelry Bonney", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4378", name: "Zorojuro", r: "Standard", t: "DEX", is_plus: true, base_id: "st3225" },
  { id: "st4354", name: "Dr. Vegapunk", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4353", name: "Bartholomew Kuma", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4350", name: "Vivi & Rebecca", r: "Standard", t: "STR", is_plus: true, base_id: "st2601" },
  { id: "st4344", name: "Donquixote Doflamingo", r: "Standard", t: "STR", is_plus: true, base_id: "st3472" },
  { id: "st4338", name: "Mr. 1", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4337", name: "Dracule Mihawk", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4336", name: "Alber", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4335", name: "Soba Mask", r: "Standard", t: "QCK", is_plus: true, base_id: "st2804" },
  { id: "st4308", name: "Nami & Sanji", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4307", name: "Usopp & Dr. Vegapunk - Lilith", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4289", name: "Vivi & Rebecca", r: "Standard", t: "STR", is_plus: true, base_id: "st3164" },
  { id: "st4288", name: "Uta", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4276", name: "Carrot & Dogstorm & Cat Viper", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4263", name: "Perona: Misty Ghost Princess", r: "Standard", t: "INT", is_plus: true, base_id: "st3454" },
  { id: "st4262", name: "Uta", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4256", name: "Magellan", r: "Standard", t: "QCK", is_plus: true, base_id: "st3278" },
  { id: "st4242", name: "Prince Grus & Kujaku & Hibari", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4240", name: "Monkey D. Garp", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4238", name: "Nefeltari Vivi", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4237", name: "Basil Hawkins", r: "Standard", t: "DEX", is_plus: true, base_id: "st2982" },
  { id: "st4233", name: "Dorry & Broggy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4221", name: "Kuzan", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4213", name: "Momonosuke & Kin'emon & Denjiro", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4202", name: "Jinbe", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4199", name: "Boa Hancock", r: "Standard", t: "PSY", is_plus: true, base_id: "st3038" },
  { id: "st4187", name: "Nico Robin", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4186", name: "Nami", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4185", name: "Trafalgar Law", r: "Standard", t: "PSY", is_plus: true, base_id: "st3027" },
  { id: "st4172", name: "Sanji", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4171", name: "Roronoa Zoro", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4170", name: "Rob Lucci", r: "Standard", t: "DEX", is_plus: true, base_id: "st3422" },
  { id: "st4142", name: "Kid & Killer", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4140", name: "Law & Bepo", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4139", name: "Jewelry Bonney", r: "Standard", t: "INT", is_plus: true, base_id: "st3307" },
  { id: "st4124", name: "Moria & Perona", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4122", name: "Doflamingo & Sugar", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4118", name: "Arlong Pirates", r: "Standard", t: "STR", is_plus: true, base_id: "st2860" },
  { id: "st4102", name: "Jesus Burgess", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st4098", name: "Silvers Rayleigh", r: "Standard", t: "PSY", is_plus: true, base_id: "st2897" },
  { id: "st4096", name: "Boa Hancock", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st4084", name: "Jewelry Bonney", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4082", name: "Dr. Vegapunk - Lilith", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st4080", name: "Kaido", r: "Standard", t: "QCK", is_plus: true, base_id: "st3227" },
  { id: "st4068", name: "Portgas D. Ace", r: "Standard", t: "STR", is_plus: true, base_id: "st4067" },
  { id: "st4056", name: "Red-Haired Shanks", r: "Standard", t: "INT", is_plus: true, base_id: "st2007" },
  { id: "st4043", name: "Kozuki Hiyori", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4041", name: "Kozuki Momonosuke", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st4037", name: "Monkey D. Luffy", r: "Standard", t: "PSY", is_plus: true, base_id: "st2672" },
  { id: "st4020", name: "Katakuri & Oven", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st4010", name: "Black Arm Zephyr", r: "Standard", t: "QCK", is_plus: true, base_id: "st2330" },
  { id: "st4000", name: "Gild Tesoro", r: "Standard", t: "QCK", is_plus: true, base_id: "st2099" },
  { id: "st3995", name: "Kizaru & Fujitora", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3993", name: "Uta", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3989", name: "Whitebeard & Marco", r: "Standard", t: "STR", is_plus: true, base_id: "st2181" },
  { id: "st3986", name: "Kurozumi Kanjuro", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3969", name: "Sanji & Judge", r: "Standard", t: "STR", is_plus: true, base_id: "st2446" },
  { id: "st3959", name: "Kozuki Momonosuke", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3948", name: "Izo", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3944", name: "Vivi & Rebecca & Shirahoshi & Mansherry", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3940", name: "Nami & Robin", r: "Standard", t: "STR", is_plus: true, base_id: "st2835" },
  { id: "st3924", name: "Black Maria & Ulti", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3922", name: "Robin & Koala", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3920", name: "Luffy & Ace", r: "Standard", t: "STR", is_plus: true, base_id: "st1985" },
  { id: "st3910", name: "Shanks & Buggy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3908", name: "Whitebeard VS Blackbeard", r: "Standard", t: "VS", is_plus: false, base_id: null },
  { id: "st3902", name: "Zeus & Prometheus & Big Mom", r: "Standard", t: "STR", is_plus: true, base_id: "st2536" },
  { id: "st3898", name: "Alber", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3891", name: "Queen", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3870", name: "Jack the Drought", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3868", name: "Bartolomeo & Hakuba", r: "Standard", t: "STR", is_plus: true, base_id: "st2418" },
  { id: "st3852", name: "Basil Hawkins", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3850", name: "Killer", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3845", name: "Red-Haired Shanks", r: "Standard", t: "STR", is_plus: true, base_id: "st2862" },
  { id: "st3828", name: "Dogstorm & Cat Viper", r: "Standard", t: "STR", is_plus: true, base_id: "st2577" },
  { id: "st3811", name: "Rayleigh & Gaban", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3809", name: "Edward Newgate", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3805", name: "Sugar", r: "Standard", t: "QCK", is_plus: true, base_id: "st3009" },
  { id: "st3784", name: "Tony Tony Chopper", r: "Standard", t: "PSY", is_plus: true, base_id: "st2797" },
  { id: "st3766", name: "Olin the Oiran", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3762", name: "Eustass Kid", r: "Standard", t: "DEX", is_plus: true, base_id: "st2980" },
  { id: "st3742", name: "Ace: Riot Flame Wolf", r: "Standard", t: "INT", is_plus: true, base_id: "st2741" },
  { id: "st3741", name: "Corazon & Law: Moonlight Day", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3739", name: "Blackbeard", r: "Standard", t: "INT", is_plus: true, base_id: "st2964" },
  { id: "st3723", name: "Buddha Sengoku", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3718", name: "Sabo", r: "Standard", t: "PSY", is_plus: true, base_id: "st2960" },
  { id: "st3708", name: "Usopp & Yasopp", r: "Standard", t: "STR", is_plus: false, base_id: "st3707" },
  { id: "st3697", name: "Ben Beckman & Lucky Roux", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3693", name: "Shiki the Golden Lion", r: "Standard", t: "QCK", is_plus: true, base_id: "st2201" },
  { id: "st3682", name: "Tony Tony Chopper", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3676", name: "Hiyori", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3674", name: "Ulti", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3670", name: "Zoro & Sanji", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3666", name: "Charlotte Katakuri", r: "Standard", t: "PSY", is_plus: true, base_id: "st2365" },
  { id: "st3654", name: "Sasaki", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3652", name: "Who's", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3650", name: "Black Maria", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3631", name: "Eustass Kid", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3629", name: "Trafalgar Law", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3625", name: "Fleet Admiral Sakazuki", r: "Standard", t: "INT", is_plus: true, base_id: "st2023" },
  { id: "st3597", name: "Olin the Oiran", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3595", name: "Marco", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3592", name: "Kuzan", r: "Standard", t: "PSY", is_plus: true, base_id: "st2025" },
  { id: "st3576", name: "Brook", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3574", name: "General Franky", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3555", name: "Kin'emon & Denjiro", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3553", name: "Kozuki Oden", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3550", name: "Donquixote Doflamingo", r: "Standard", t: "DEX", is_plus: true, base_id: "st1910" },
  { id: "st3536", name: "Cat Viper", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3534", name: "Dogstorm", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3510", name: "Brook", r: "Standard", t: "DEX", is_plus: true, base_id: "st2236" },
  { id: "st3495", name: "Robin & Jinbe", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3493", name: "Nami & Usopp", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3474", name: "Charlotte Katakuri", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3472", name: "Donquixote Doflamingo", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3469", name: "Charlotte Pudding", r: "Standard", t: "INT", is_plus: true, base_id: "st2837" },
  { id: "st3454", name: "Perona: Halloween Ghost Princess", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3452", name: "Hancock: Sweet Flirtatious Halloween", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3448", name: "Jack", r: "Standard", t: "STR", is_plus: true, base_id: "st2433" },
  { id: "st3433", name: "Ulti & Page One", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3422", name: "Rob Lucci", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3417", name: "Carrot", r: "Standard", t: "QCK", is_plus: true, base_id: "st2338" },
  { id: "st3405", name: "Vivi", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3403", name: "Reiju", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3398", name: "Straw Hat Pirates", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3393", name: "Sabo", r: "Standard", t: "DEX", is_plus: true, base_id: "st2441" },
  { id: "st3378", name: "Queen the Plague", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3376", name: "King the Wildfire", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3369", name: "Germa 66", r: "Standard", t: "PSY", is_plus: true, base_id: "st3071" },
  { id: "st3357", name: "Marco", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3355", name: "Whitebeard VS Shanks", r: "Standard", t: "VS", is_plus: false, base_id: null },
  { id: "st3350", name: "Komurasaki", r: "Standard", t: "INT", is_plus: true, base_id: "st2776" },
  { id: "st3307", name: "Jewelry Bonney", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3298", name: "Charlotte Cracker", r: "Standard", t: "QCK", is_plus: true, base_id: "st2465" },
  { id: "st3282", name: "Gecko Moria", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3280", name: "Blackbeard", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3278", name: "Magellan", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3275", name: "Onami", r: "Standard", t: "QCK", is_plus: true, base_id: "st2774" },
  { id: "st3253", name: "Ace VS Akainu", r: "Standard", t: "VS", is_plus: false, base_id: null },
  { id: "st3240", name: "Hawk Eyes Mihawk", r: "Standard", t: "DEX", is_plus: true, base_id: "st2475" },
  { id: "st3227", name: "Kaido", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3225", name: "Zorojuro", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st3211", name: "Sanji", r: "Standard", t: "PSY", is_plus: true, base_id: "st2148" },
  { id: "st3202", name: "Roronoa Zoro", r: "Standard", t: "INT", is_plus: true, base_id: "st2477" },
  { id: "st3166", name: "Shirahoshi & Mansherry", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3164", name: "Vivi & Rebecca", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3154", name: "Blackbeard", r: "Standard", t: "DEX", is_plus: true, base_id: "st1268" },
  { id: "st3135", name: "Kaido VS Big Mom", r: "Standard", t: "VS", is_plus: false, base_id: null },
  { id: "st3118", name: "Shanks: Moon Knight King", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3102", name: "Law: Midnight Lord", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3100", name: "Mihawk: Lord of the Never", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st3079", name: "Capone Bege", r: "Standard", t: "INT", is_plus: true, base_id: "st2302" },
  { id: "st3073", name: "Sweet 3 Generals", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3071", name: "Germa 66", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3065", name: "Luffy & Sanji", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st3048", name: "Knight of the Sea Jinbe", r: "Standard", t: "DEX", is_plus: true, base_id: "st2265" },
  { id: "st3038", name: "Boa Hancock", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3027", name: "Trafalgar Law", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st3018", name: "Dark King Rayleigh", r: "Standard", t: "DEX", is_plus: true, base_id: "st1883" },
  { id: "st3009", name: "Sugar", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st3007", name: "Smoker the White Hunter", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2991", name: "Garp the Fist", r: "Standard", t: "PSY", is_plus: true, base_id: "st2251" },
  { id: "st2982", name: "Basil Hawkins the Magician", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2980", name: "Eustass Kid", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2964", name: "Blackbeard", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2962", name: "Charlotte Katakuri", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2960", name: "Sabo", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2958", name: "Monkey D. Luffy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2954", name: "Fujitora", r: "Standard", t: "INT", is_plus: true, base_id: "st1085" },
  { id: "st2909", name: "Whitebeard", r: "Standard", t: "QCK", is_plus: true, base_id: "st2686" },
  { id: "st2897", name: "Dark King Rayleigh", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2895", name: "Mihawk & Perona", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2868", name: "Marco the Phoenix", r: "Standard", t: "QCK", is_plus: true, base_id: "st0649" },
  { id: "st2862", name: "Red-Haired Shanks", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2860", name: "Arlong Pirates", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2837", name: "Charlotte Pudding", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2835", name: "Nami & Robin", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2830", name: "Nico Robin", r: "Standard", t: "INT", is_plus: true, base_id: "st1951" },
  { id: "st2814", name: "Sabo: Revolutionary Army Chief of Staff", r: "Standard", t: "QCK", is_plus: true, base_id: "st1794" },
  { id: "st2804", name: "Soba Mask", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2802", name: "Luffytaro & Zorojuro", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2797", name: "Tony Tony Chopper", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2784", name: "Lucci: Beastman", r: "Standard", t: "QCK", is_plus: true, base_id: "st1763" },
  { id: "st2776", name: "Komurasaki the Oiran", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2774", name: "Onami", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2741", name: "Ace: Trickster Flame Wolf", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2739", name: "Katakuri", r: "Standard", t: "INT", is_plus: true, base_id: "st2113" },
  { id: "st2700", name: "Kaido", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2686", name: "Whitebeard", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2681", name: "Douglas Bullet", r: "Standard", t: "STR", is_plus: true, base_id: "st2651" },
  { id: "st2672", name: "Monkey D. Luffy", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2651", name: "Douglas Bullet", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2631", name: "Princess Shirahoshi", r: "Standard", t: "PSY", is_plus: true, base_id: "st1473" },
  { id: "st2603", name: "Shirahoshi & Mansherry", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2601", name: "Vivi & Rebecca", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2588", name: "Nami", r: "Standard", t: "DEX", is_plus: true, base_id: "st2076" },
  { id: "st2578", name: "Fleet Admiral Sakazuki", r: "Standard", t: "STR", is_plus: true, base_id: "st1314" },
  { id: "st2577", name: "Dogstorm & Cat Viper", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2561", name: "Sabo & Koala", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2536", name: "Zeus & Prometheus & Big Mom", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2534", name: "Luffy & Law", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2505", name: "Fujitora", r: "Standard", t: "INT", is_plus: true, base_id: "st1869" },
  { id: "st2500", name: "Big Mom", r: "Standard", t: "STR", is_plus: true, base_id: "st2234" },
  { id: "st2477", name: "Roronoa Zoro", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2475", name: "Dracule Mihawk", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2465", name: "Charlotte Cracker", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2446", name: "Sanji & Judge", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2444", name: "Donquixote Doflamingo", r: "Standard", t: "INT", is_plus: true, base_id: "st0870" },
  { id: "st2441", name: "Sabo", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2434", name: "Boa Hancock", r: "Standard", t: "PSY", is_plus: true, base_id: "st1747" },
  { id: "st2433", name: "Jack", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2418", name: "Bartolomeo & Cavendish", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2373", name: "Cat Viper", r: "Standard", t: "PSY", is_plus: true, base_id: "st1652" },
  { id: "st2372", name: "Dogstorm", r: "Standard", t: "STR", is_plus: true, base_id: "st1571" },
  { id: "st2365", name: "Charlotte Katakuri", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2363", name: "Monkey D. Luffy", r: "Standard", t: "STR", is_plus: true, base_id: "st2074" },
  { id: "st2357", name: "Hakuba", r: "Standard", t: "QCK", is_plus: true, base_id: "st1123" },
  { id: "st2338", name: "Carrot", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2330", name: "Black Arm Zephyr", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2302", name: "Capone Bege", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2300", name: "Franky", r: "Standard", t: "QCK", is_plus: true, base_id: "st1935" },
  { id: "st2265", name: "Knight of the Sea Jinbe", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2251", name: "Garp the Fist", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2245", name: "Sanji", r: "Standard", t: "INT", is_plus: true, base_id: "st1588" },
  { id: "st2236", name: "Soul King Brook", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2234", name: "Big Mom", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2232", name: "Kami Eneru", r: "Standard", t: "QCK", is_plus: true, base_id: "st1610" },
  { id: "st2201", name: "Shiki", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2195", name: "Cora", r: "Standard", t: "DEX", is_plus: true, base_id: "st1001" },
  { id: "st2181", name: "Whitebeard & Marco", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2159", name: "Magellan", r: "Standard", t: "DEX", is_plus: true, base_id: "st1698" },
  { id: "st2148", name: "Vinsmoke Sanji", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2138", name: "Vinsmoke Judge", r: "Standard", t: "INT", is_plus: true, base_id: "st1832" },
  { id: "st2113", name: "Charlotte Katakuri", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st2099", name: "Golden Tesoro", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2076", name: "Nami", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st2074", name: "Straw Hat Luffy", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st2066", name: "Knight of the Sea Jinbe", r: "Standard", t: "INT", is_plus: true, base_id: "st0935" },
  { id: "st2035", name: "Buggy the Genius Jester", r: "Standard", t: "INT", is_plus: true, base_id: "st1391" },
  { id: "st2034", name: "Borsalino", r: "Standard", t: "PSY", is_plus: true, base_id: "st1240" },
  { id: "st2025", name: "Kuzan", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st2023", name: "Sakazuki", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2007", name: "Red-Haired Shanks", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st2001", name: "Trafalgar Law", r: "Standard", t: "PSY", is_plus: true, base_id: "st1045" },
  { id: "st1985", name: "Luffy & Ace", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1951", name: "Nico Robin", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1935", name: "Franky", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1928", name: "Man", r: "Standard", t: "QCK", is_plus: true, base_id: "st1035" },
  { id: "st1927", name: "Sir Crocodile", r: "Standard", t: "STR", is_plus: true, base_id: "st0720" },
  { id: "st1922", name: "Trafalgar Law", r: "Standard", t: "QCK", is_plus: true, base_id: "st1751" },
  { id: "st1921", name: "Zoro the Pirate Hunter", r: "Standard", t: "DEX", is_plus: true, base_id: "st1362" },
  { id: "st1910", name: "Heavenly Demon Doflamingo", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1883", name: "Dark King Rayleigh", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1881", name: "Hawk Eyes Mihawk", r: "Standard", t: "INT", is_plus: true, base_id: "st0718" },
  { id: "st1880", name: "Hody Jones", r: "Standard", t: "INT", is_plus: true, base_id: "st1434" },
  { id: "st1869", name: "Issho", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st1847", name: "Sengoku", r: "Standard", t: "INT", is_plus: true, base_id: "st0459" },
  { id: "st1832", name: "Vinsmoke Judge", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1816", name: "Portgas D. Ace", r: "Standard", t: "DEX", is_plus: true, base_id: "st0562" },
  { id: "st1794", name: "Lucy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1764", name: "Kuzan", r: "Standard", t: "QCK", is_plus: true, base_id: "st1192" },
  { id: "st1763", name: "Lucci: Beastman", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1751", name: "Trafalgar Law", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1747", name: "Boa Hancock", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1707", name: "Red-Haired Shanks", r: "Standard", t: "PSY", is_plus: true, base_id: "st0530" },
  { id: "st1698", name: "Magellan", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1663", name: "Rob Lucci", r: "Standard", t: "STR", is_plus: true, base_id: "st0748" },
  { id: "st1652", name: "Cat Viper: King of the Night", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1619", name: "The Dark King Silvers Rayleigh", r: "Standard", t: "INT", is_plus: true, base_id: "st0367" },
  { id: "st1610", name: "Kami Eneru", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1593", name: "Monkey D. Luffy", r: "Standard", t: "PSY", is_plus: true, base_id: "st1404" },
  { id: "st1588", name: "Sanji", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st1571", name: "Dogstorm: King of the Day", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1543", name: "Captain Usopp", r: "Standard", t: "DEX", is_plus: true, base_id: "st1532" },
  { id: "st1532", name: "God Usopp", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1492", name: "Sabo", r: "Standard", t: "PSY", is_plus: true, base_id: "st0669" },
  { id: "st1473", name: "Princess Shirahoshi", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1445", name: "Boa Hancock", r: "Standard", t: "QCK", is_plus: true, base_id: "st0416" },
  { id: "st1434", name: "Hody Jones", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st1413", name: "Whitebeard", r: "Standard", t: "STR", is_plus: true, base_id: "st0261" },
  { id: "st1404", name: "Monkey D. Luffy", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1391", name: "Captain Buggy", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st1362", name: "Roronoa Zoro", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1314", name: "Sakazuki", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1268", name: "Blackbeard", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st1240", name: "Borsalino", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1192", name: "Kuzan", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1123", name: "White Knight Cavendish", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st1121", name: "Monkey D. Luffy", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1085", name: "Issho", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st1045", name: "Trafalgar Law", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st1035", name: "Bartolomeo", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st1001", name: "Donquixote Rocinante", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st0935", name: "Knight of the Sea Jinbe", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st0870", name: "Heavenly Demon Doflamingo", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st0748", name: "Rob Lucci", r: "Standard", t: "STR", is_plus: false, base_id: null },
  { id: "st0720", name: "Sir Crocodile: Logia", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st0718", name: "Hawk Eyes Mihawk", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st0669", name: "Sabo", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st0649", name: "Marco the Phoenix", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st0562", name: "Portgas D. Ace", r: "Standard", t: "DEX", is_plus: false, base_id: null },
  { id: "st0530", name: "Shanks", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st0459", name: "Sengoku the Buddha", r: "Standard", t: "PSY", is_plus: false, base_id: null },
  { id: "st0416", name: "Boa Hancock", r: "Standard", t: "QCK", is_plus: false, base_id: null },
  { id: "st0367", name: "Dark King Rayleigh", r: "Standard", t: "INT", is_plus: false, base_id: null },
  { id: "st0261", name: "Whitebeard", r: "Standard", t: "STR", is_plus: false, base_id: null },
];
